version: "3.8"

services:
  backend:
    build: ./backend
    container_name: vocabtai-backend
    depends_on:
      - db
    expose:
      - "4000"
    networks:
      - app-network

  frontend:
    build: ./todolist
    container_name: vocabtai-frontend
    env_file:
      - ./todolist/.env
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: vocabtai-db
    restart: always
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 141421
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: vocabtai-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
